#!/usr/bin/env python3
"""Draft Farcaster + X social posts for a BCZ YapZ episode.

Mirrors the on-site ShareButtons logic: parses guest_links, builds an
excited first-person share text with guests + host @-tagged, generates
the Farcaster compose URL + X intent URL. Writes a drafts file to
content/socials/<slug>.md and prints to stdout.

Usage:
  python3 scripts/draft-socials.py --slug 2026-05-12-eriks-jonathan-fotocaster
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.parse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TRANSCRIPTS_DIR = REPO / "content" / "transcripts"
SOCIALS_DIR = REPO / "content" / "socials"
SITE_URL = "https://bczyapz.com"
HOST_FC = "@zaal"
HOST_X = "@bettercallzaal"


def read_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        raise SystemExit(f"no frontmatter in {path}")
    raw = m.group(1)
    fm: dict = {"guest_links": []}
    current_list_key: str | None = None
    for line in raw.splitlines():
        if re.match(r"^  - ", line) and current_list_key:
            val = line[4:].strip()
            if val.startswith('"') or val.startswith("'"):
                val = val.strip("\"'")
            fm.setdefault(current_list_key, []).append(val)
            continue
        if re.match(r"^[a-z_]+:\s*$", line):
            current_list_key = line.split(":")[0]
            fm[current_list_key] = []
            continue
        m2 = re.match(r"^([a-z_]+):\s*(.+)$", line)
        if m2:
            current_list_key = None
            k, v = m2.group(1), m2.group(2).strip()
            v = v.strip("\"'")
            fm[k] = v
    return fm


def parse_handles(links: list[str], platform: str) -> list[str]:
    out: list[str] = []
    for link in links:
        m = re.match(r"^\s*(\w+)\s*:\s*(.+)$", link)
        if not m:
            continue
        if m.group(1).lower() != platform:
            continue
        h = m.group(2).strip()
        if h.startswith("@") and h not in out:
            out.append(h)
    return out


def join_handles(handles: list[str], fallback: str) -> str:
    if not handles:
        return fallback
    if len(handles) == 1:
        return handles[0]
    if len(handles) == 2:
        return f"{handles[0]} and {handles[1]}"
    return ", ".join(handles[:-1]) + f", and {handles[-1]}"


def build_drafts(slug: str, fm: dict) -> dict:
    guest = fm.get("guest", "")
    org = fm.get("guest_org", "")
    org_suffix = f" ({org})" if org else ""
    links = fm.get("guest_links", []) or []
    fc_guests = join_handles(parse_handles(links, "farcaster"), guest)
    x_guests = join_handles(parse_handles(links, "x"), guest)

    url = f"{SITE_URL}/ep/{slug}"
    fc_text = (
        f"Just watched {fc_guests}{org_suffix} on {HOST_FC}'s BCZ YapZ - "
        f"great conversation, worth a watch:"
    )
    x_text = (
        f"Just watched {x_guests}{org_suffix} on {HOST_X}'s BCZ YapZ - "
        f"great conversation, worth a watch:"
    )

    fc_url = (
        f"https://farcaster.xyz/~/compose?text={urllib.parse.quote(fc_text)}"
        f"&embeds[]={urllib.parse.quote(url)}"
    )
    x_url = (
        f"https://x.com/intent/post?text={urllib.parse.quote(x_text)}"
        f"&url={urllib.parse.quote(url)}"
    )

    return {
        "url": url,
        "fc_text": fc_text,
        "x_text": x_text,
        "fc_url": fc_url,
        "x_url": x_url,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--slug", required=True, help="transcript filename without .md")
    args = ap.parse_args()

    path = TRANSCRIPTS_DIR / f"{args.slug}.md"
    if not path.exists():
        print(f"error: {path} not found", file=sys.stderr)
        sys.exit(1)

    fm = read_frontmatter(path)
    drafts = build_drafts(args.slug, fm)

    out = f"""# Social drafts - {args.slug}

Generated by scripts/draft-socials.py. Edit before posting.

## Farcaster

{drafts['fc_text']}

{drafts['url']}

One-click compose:
{drafts['fc_url']}

## X

{drafts['x_text']}

{drafts['url']}

One-click compose:
{drafts['x_url']}
"""

    SOCIALS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = SOCIALS_DIR / f"{args.slug}.md"
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO)}")
    print()
    print(out)


if __name__ == "__main__":
    main()
